import type { TourDefinition } from './types'
import {
  A_ORG_STATS,
  A_ORG_QUICK_ACTIONS,
  A_ATHLETES_ADD,
  A_ATHLETES_IMPORT,
  A_TEAMS_CREATE_HEADER,
  A_TEAMS_CREATE_EMPTY,
  A_EVENTS_CREATE_HEADER,
  A_EVENTS_CREATE_EMPTY,
  A_ANALYTICS_ROOT,
  A_ANNOUNCEMENTS_NEW,
  navAnchor,
} from './anchors'

export const organizerTour: TourDefinition = {
  id: 'organizer',
  version: 1,
  label: 'Organizer: run a season',
  description: 'Where athletes, teams, events, and live scoring live, and how they connect.',
  roles: ['Organizer'],
  steps: [
    {
      id: 'welcome',
      title: 'Welcome to U-Sports',
      body: "A quick tour of your dashboard. You'll see the same season your Super Admin set up for you — sports and dates are already scoped, so every form below only shows what actually applies to you.",
    },
    {
      id: 'stats',
      route: '/organizer',
      target: A_ORG_STATS,
      title: 'Your season at a glance',
      body: 'Your events, live matches, and assigned sports.',
    },
    {
      id: 'quick-actions',
      target: A_ORG_QUICK_ACTIONS,
      title: 'Quick actions',
      body: 'The four things you do most — start here to jump straight to any of them.',
    },
    {
      id: 'athletes-nav',
      route: '/organizer/athletes',
      target: navAnchor('/organizer/athletes'),
      title: 'Athletes',
      body: "Every athlete in the system — add them one at a time, or import a whole roster from a spreadsheet.",
      interactive: true,
    },
    {
      id: 'athletes-add',
      target: [A_ATHLETES_ADD, A_ATHLETES_IMPORT],
      title: 'Add or import athletes',
      body: 'Add one athlete directly, or import a spreadsheet for a whole roster at once — either sends the athlete an email invite to set up their account.',
      interactive: true,
    },
    {
      id: 'teams-nav',
      route: '/organizer/teams',
      target: navAnchor('/organizer/teams'),
      title: 'Teams',
      body: 'Rosters, active lineups, and jersey numbers all live here — not on the Athletes page.',
      interactive: true,
    },
    {
      id: 'teams-create',
      target: [A_TEAMS_CREATE_HEADER, A_TEAMS_CREATE_EMPTY],
      title: 'Create a team',
      body: "Pick the season first — the sport list narrows to whatever that season actually carries.",
      interactive: true,
    },
    {
      id: 'events-nav',
      route: '/organizer/events',
      target: navAnchor('/organizer/events'),
      title: 'Events',
      body: 'Brackets and schedules. Live scoring is reached from an event\'s matches once it starts.',
      interactive: true,
    },
    {
      id: 'events-create',
      target: [A_EVENTS_CREATE_HEADER, A_EVENTS_CREATE_EMPTY],
      title: 'Create an event',
      body: 'Same rule as Teams — season first, then the sport and format narrow to match.',
      interactive: true,
    },
    {
      id: 'analytics-nav',
      route: '/organizer/analytics',
      target: navAnchor('/organizer/analytics'),
      title: 'Analytics',
      body: 'Leaderboards, standings, and trending performance — updates automatically as matches finish.',
      interactive: true,
    },
    {
      id: 'analytics-root',
      target: A_ANALYTICS_ROOT,
      title: 'Trends and leaderboards',
      body: "Trending Up/Down surfaces athletes whose recent games differ from their season average — worth checking after every few completed matches.",
      interactive: true,
    },
    {
      id: 'announcements-nav',
      route: '/organizer/announcements',
      target: navAnchor('/organizer/announcements'),
      title: 'Announcements',
      body: 'Broadcast messages to athletes and the public — schedule changes, venue moves, anything everyone needs to see at once.',
      interactive: true,
    },
    {
      id: 'announcements-new',
      target: A_ANNOUNCEMENTS_NEW,
      title: 'Post an announcement',
      required: false,
      interactive: true,
      body: 'Athletes on the affected sport get a notification the moment you post.',
    },
    {
      id: 'done',
      title: "That's the whole loop",
      body: 'Athletes → Teams → Events → score matches live → Analytics tracks it automatically. Replay this any time from Settings → Help Center.',
    },
  ],
}
